Emily Rickman
Personal Website 
markdown: kramdown
theme: midnight 

title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
